---
abstract: 'Inject constants & constructors for ARRAY-type objects'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-ArrayType-New
requires:
  B: 0
  Carp: 0
  Scalar::Util: 0
  perl: v5.8.1
resources:
  repository: git://github.com/avenj/object-arraytype-new.git
version: 0.002002
